name: ci
on: push

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose build
      - name: pnpm install
        run: docker compose run --rm web pnpm install
      - name: lint
        run: docker compose run --rm web pnpm lint
